version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      # Check for updates to Rust crates every week
      interval: "weekly"
    groups:
      minor:
        update-types: ["minor", "patch"]
